/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 newmodel.gltf
Author: StraXartS (https://sketchfab.com/Strax123trt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pennywise-the-dancing-clown-it-b5d5075716f14557beb55175f415a836
Title: Pennywise the Dancing Clown IT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/newmodel.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/newmodel.gltf')
